// Generated by CoffeeScript 1.4.0
(function() {
  var main;

  main = function() {
    var buttons, example, lang, lang_key, xml_editor, _fn, _i, _len, _ref, _ref1, _ref2;
    load_form();
    init_brat();
    xml_editor = CodeMirror.fromTextArea(document.getElementById("corpus_xml"), {
      lineNumbers: true
    });
    xml_editor.setValue("En exempeltext kommer lastad. Med vadå?");
    buttons = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = examples.length; _i < _len; _i++) {
        example = examples[_i];
        _results.push((function(example) {
          return $("<button class=\"btn-small btn-info\" style=\"margin:5px;\"\">\n    <i class=\"icon-book\"></i> " + example.title + "\n</button>").click(function() {
            return with_form.set(xml_editor, example);
          });
        })(example));
      }
      return _results;
    })();
    _ref = [["se", "Svenska"], ["en", "English"]];
    _fn = function(lang_key, lang) {
      var button;
      button = $("<button class=\"btn-small btn-warning\" style=\"margin:5px;\"\">\n    <i class=\"icon-bookmark-empty\"></i> " + lang + "\n</button>").click(function() {
        return $.fn.set_language(lang_key);
      });
      return buttons.push(button);
    };
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      _ref1 = _ref[_i], lang_key = _ref1[0], lang = _ref1[1];
      _fn(lang_key, lang);
    }
    (_ref2 = $("#example_buttons")).append.apply(_ref2, buttons);
    $("#show_query").click(function() {
      submit(xml_editor, "makefile");
      return false;
    });
    $("#btn_submit").click(function() {
      submit(xml_editor, "xml");
      return false;
    });
    return $("#btn_install").click(function() {
      submit(xml_editor, "cwb");
      return false;
    });
  };

  $(document).ready(main);

}).call(this);
