// Generated by CoffeeScript 1.4.0
(function() {
  var set_form,
    __slice = [].slice;

  window.loadExample = function() {
    return console.log("Error: Form not loaded!");
  };

  window.mkJsonSetting = function() {
    return console.log("Error: Form not loaded!");
  };

  set_form = function(schema, value) {
    var form;
    form = json_schema_form.generate(schema, "settings");
    $("#form").empty().append(form.dom);
    form.set(value);
    window.loadExample = function(xml_editor, example) {
      xml_editor.setValue(example.corpus_xml);
      return form.set(example);
    };
    return window.mkJsonSetting = form.get;
  };

  window.load_form = function() {
    return $.ajax({
      url: "http://localhost:8051",
      data: {
        format: "schema"
      },
      dataType: "json",
      timeout: 300000,
      type: "GET",
      success: function(data, textStatus, xhr) {
        var defaults, schema;
        schema = json_schema_utils.flatten_singleton_unions(json_schema_utils.follow_references(data));
        defaults = json_schema_utils.get_default(schema);
        console.log(schema, defaults);
        return set_form(schema, defaults);
      },
      error: function() {
        var info;
        info = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return console.log(info);
      }
    });
  };

}).call(this);
