
window.pos_localization =
    se:
        "VB" : "Verb"
        "AB" : "Adverb"
        "DT" : "Bestämningsord, bestämd artikel"
        "HA" : "Frågande/relativt adverb"
        "HD" : "Frågande/relativ bestämning"
        "HP" : "Frågande/relativt pronomen"
        "HS" : "Frågande/relativt possesivuttryck"
        "IE" : "Infinitivmärke"
        "IN" : "Interjektion"
        "JJ" : "Adjektiv"
        "KN" : "Konjunktion"
        "NN" : "Substantiv"
        "PC" : "Particip"
        "PL" : "Partikel"
        "PM" : "Egennamn"
        "PN" : "Pronomen"
        "PP" : "Preposition"
        "PS" : "Possesivuttryck"
        "RG" : "Räkneord: grundtal"
        "RO" : "Räkneord: ordningstal"
        "SN" : "Subjunktion"
        "UO" : "Utländskt ord"
        "MAD" : "Meningsskiljande interpunktion"
    en:
        "VB" : "Verb"
        "AB" : "Adverb"
        "DT" : "Determiner"
        "HA" : "Interrogative/Relative Adverb"
        "HD" : "Interrogative/Relative Determiner"
        "HP" : "Interrogative/Relative Pronoun"
        "HS" : "Interrogative/Relative Possessive"
        "IE" : "Infinitive Marker"
        "IN" : "Interjection"
        "JJ" : "Adjective"
        "KN" : "Conjunction"
        "NN" : "Noun"
        "PC" : "Participle"
        "PL" : "Particle"
        "PM" : "Proper Noun"
        "PN" : "Pronoun"
        "PP" : "Preposition"
        "PS" : "Possessive"
        "RG" : "Cardinal Number"
        "RO" : "Ordinal Number"
        "SN" : "Subjunction"
        "UO" : "Foreign Word"
        "VB" : "Verb"
        "MAD" : "Separative Sentence Interpunctation"

