// Generated by CoffeeScript 1.4.0
(function() {

  window.progress = {};

  progress.initialize = function() {
    $('#progress-div').css("display", "");
    $('#progress-bar').css("width", "0%");
    return $('#progress-text').text("");
  };

  progress.clear = function() {
    $('#progress-div').css("display", "none");
    $('#progress-bar').css("width", "0%");
    return $('#progress-text').text("");
  };

  progress.handle = function(data) {
    var command, increment, json, percent, step, steps;
    if (-1 !== data.indexOf('</result>')) {
      progress.clear();
      return;
    } else {
      data += '</result>';
    }
    json = $.xml2json(data);
    if (increment = _.last(json.increment)) {
      steps = Number(increment.steps);
      step = Number(increment.step);
      command = increment.command;
      percent = steps > 0 ? step / steps * 100 : 100;
      $('#progress-bar').css("width", percent + '%');
      if (command != null) {
        return $('#progress-text').localize_element({
          se: "Kör kommando " + command + "...",
          en: "Running command " + command + "..."
        });
      } else {
        return $('#progress-text').localize_element({
          se: "",
          en: ""
        });
      }
    }
  };

}).call(this);
