// Generated by CoffeeScript 1.4.0
(function() {

  window.progress = {};

  progress.initialize = function() {
    $('#progress-div').css("display", "");
    $('#progress-bar').css("width", "0%");
    return $('#progress-text').text("");
  };

  progress.clear = function() {
    $('#progress-div').css("display", "none");
    $('#progress-bar').css("width", "0%");
    return $('#progress-text').text("");
  };

  progress.handle = function(data) {
    var command, finished, i, ilen, json, percent, step, steps;
    finished = -1 !== data.indexOf('</result>');
    if (finished) {
      progress.clear();
      return;
    }
    if (-1 === data.indexOf('</incremental>')) {
      data += '</incremental>';
    }
    data += '</result>';
    json = $.xml2json(data);
    percent = 100;
    command = "";
    i = json.incremental;
    if (i) {
      steps = (Number(i.steps)) + 1;
      step = 0;
      if (i.increment) {
        ilen = i.increment.length;
        if (ilen > 0) {
          step = i.increment[ilen - 1].step;
          command = i.increment[ilen - 1].command;
        }
      }
      percent = steps > 0 ? step / steps * 100 : 100;
      if (command != null) {
        $('#progress-text').text("Kör kommando " + command + "...");
      } else {
        $('#progress-text').text("");
      }
      return $('#progress-bar').css("width", percent + '%');
    }
  };

}).call(this);
