// Generated by CoffeeScript 1.4.0
(function() {

  window.FormCtrl = function($scope) {
    $scope.schema = {
      object: {
        title: "Object",
        type: "object",
        properties: {
          happy: {
            title: "Happy",
            type: "bool"
          },
          name: {
            title: "Name",
            type: "string"
          }
        }
      },
      objlist: {
        title: "Object List",
        type: "array",
        items: {
          title: "List Object",
          type: "object",
          "default": {
            happy: true,
            name: ""
          },
          properties: {
            happy: {
              title: "Happy",
              type: "bool"
            },
            name: {
              title: "Name",
              type: "string"
            }
          }
        }
      }
    };
    $scope.clone = function(obj) {
      return JSON.parse(JSON.stringify(obj));
    };
    $scope.values = {
      objlist: [],
      object: {
        name: 'johan',
        happy: true
      },
      name: 'dan',
      street: 'tunnbindaregatan',
      pets: ['bosse', 'bjarne'],
      happy: true,
      i: [],
      segmenter: "punkt",
      generate: [],
      union: "w"
    };
  };

  window.app = angular.module('formModule', []);

}).call(this);
