// Generated by CoffeeScript 1.4.0
(function() {

  window.Ctrl3 = function($scope) {
    $scope.title = 'le nu binxo';
    return $scope.text = 'ma tavla fi ma';
  };

  angular.module('zippyModule', []).directive('zippy', function() {
    return {
      restrict: 'C',
      replace: true,
      transclude: true,
      scrope: {
        title: '@zippyTitle'
      },
      template: '<div>\n    <div class="title">{{title}}</div>\n    <div class="body" ng-transclude>\n        Title: <input ng-model="title"><br>\n        Text: <textarea ng-model="text"></textarea>\n        <hr>\n        {{text}}\n    </div>\n</div>',
      link: function(scope, element, attrs) {
        var opened, title, toggle;
        title = angular.element(element.children()[0]);
        opened = true;
        toggle = function() {
          opened = !opened;
          element.removeClass(opened ? 'closed' : 'opened');
          element.addClass(!opened ? 'closed' : 'opened');
        };
        title.bind('click', toggle);
        return toggle();
      }
    };
  });

}).call(this);
