// Generated by CoffeeScript 1.4.0
(function() {

  app.directive('subScope', function() {
    return {
      scope: {
        desc: '=',
        values: '=',
        prop: '='
      },
      transclude: true,
      replace: true,
      compile: function(element, attr, transclude) {
        return function(scope, iElement, attr) {
          var $scope, x;
          console.log(scope);
          $scope = scope.$new();
          $scope.desc = {};
          angular.forEach(scope.desc, function(value, key) {
            console.log("desc", key, "->", value);
            return $scope.desc[key] = value;
          });
          $scope.values = (function() {
            var _i, _len, _ref, _results;
            _ref = scope.values;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              x = _ref[_i];
              _results.push(x);
            }
            return _results;
          })();
          console.log("scope.values", scope.values);
          console.log("$scope.values", $scope.values);
          $scope.prop = scope.prop;
          console.log("prop", "->", $scope.prop);
          return iElement.append(transclude($scope));
        };
      }
    };
  });

}).call(this);
