// Generated by CoffeeScript 1.4.0
(function() {
  var examples, generate, load_example, logger, test_examples, type_match,
    __slice = [].slice;

  $(window.document).ready(function() {
    var key, _fn;
    _fn = function(key) {
      var example_button;
      example_button = $("<button>" + key + "</button>").click(function() {
        load_example(examples[key]);
        return false;
      });
      return $("#examples").append(example_button);
    };
    for (key in examples) {
      _fn(key);
    }
    return load_example(examples.array);
  });

  load_example = function(example) {
    var form;
    form = generate(example.schema, "value");
    $("#form").empty().append(form.dom);
    form.set(example.value);
    return $('#get').unbind('click').click(function() {
      var v;
      v = form.get();
      console.log(v);
      console.log(JSON.stringify(v));
      return $('#result').text(JSON.stringify(v));
    });
  };

  generate = function(schema, path) {
    return (function() {
      var decorator;
      decorator = function(make) {
        var inner_dom, obj, type;
        obj = make();
        inner_dom = obj.dom;
        type = _.isArray(schema.type) ? "union" : schema.type;
        obj.dom = $("<div class=\"" + type + "\"/>");
        if (schema.title != null) {
          obj.dom.append($("<div class=\"title\">" + schema.title + "</div>"));
        }
        if (schema.description != null) {
          obj.dom.append($("<div class=\"description\">" + schema.description + "</div>"));
        }
        obj.dom.append(inner_dom);
        return obj;
      };
      return decorator(function() {
        var dom, generate_item, i, items, items_div, key, new_button, object, objects, option, option_div, options, select_dom, subschema, with_selected, _i, _j, _len, _len1;
        if (schema.type === "string") {
          return {
            dom: dom = $("<input id=\"" + path + "\">"),
            set: function(v) {
              dom.val(v);
            },
            get: function() {
              return dom.val();
            }
          };
        } else if (schema.type === "bool") {
          return {
            dom: dom = $("<input id=\"" + path + "\" type=\"checkbox\">"),
            set: function(v) {
              dom.attr('checked', v);
            },
            get: function() {
              return 'checked' === dom.attr('checked');
            }
          };
        } else if (schema.type === "object") {
          dom = $("<div class=\"object\">");
          objects = (function() {
            var _results;
            _results = [];
            for (key in schema.properties) {
              _results.push(_.extend({
                key: key
              }, generate(schema.properties[key], "" + path + "_" + key)));
            }
            return _results;
          })();
          for (_i = 0, _len = objects.length; _i < _len; _i++) {
            object = objects[_i];
            dom.append(object.dom);
          }
          return {
            dom: dom,
            set: function(obj) {
              var _j, _len1;
              for (_j = 0, _len1 = objects.length; _j < _len1; _j++) {
                object = objects[_j];
                object.set(obj[object.key]);
              }
            },
            get: function() {
              return _.object((function() {
                var _j, _len1, _results;
                _results = [];
                for (_j = 0, _len1 = objects.length; _j < _len1; _j++) {
                  object = objects[_j];
                  _results.push([object.key, object.get()]);
                }
                return _results;
              })());
            }
          };
        } else if (schema.type === "array") {
          dom = $("<div class=\"inner\">");
          items_div = $("<div class=\"items\">");
          items = [];
          generate_item = function() {
            var item, item_div, rm_button;
            item = generate(schema.items, "" + path + "_item");
            item_div = $("<div class=\"item\">");
            rm_button = $("<button>rm</button>").click(function() {
              item_div.remove();
              items = _.without(items, item);
              return false;
            });
            items_div.append(item_div.append(item.dom, rm_button));
            return item;
          };
          new_button = $("<button>mk</button>").click(function() {
            items.push(generate_item());
            return false;
          });
          return {
            dom: dom.append(new_button, items_div),
            set: function(vs) {
              var item, v;
              items_div.empty();
              items = (function() {
                var _j, _len1, _results;
                _results = [];
                for (_j = 0, _len1 = vs.length; _j < _len1; _j++) {
                  v = vs[_j];
                  item = generate_item();
                  item.set(v);
                  _results.push(item);
                }
                return _results;
              })();
            },
            get: function() {
              var item, _j, _len1, _results;
              _results = [];
              for (_j = 0, _len1 = items.length; _j < _len1; _j++) {
                item = items[_j];
                _results.push(item.get());
              }
              return _results;
            }
          };
        } else if ($.isArray(schema.type)) {
          dom = $("<div class=\"inner\">");
          select_dom = $("<select>");
          options = (function() {
            var _j, _len1, _ref, _results;
            _ref = schema.type;
            _results = [];
            for (i = _j = 0, _len1 = _ref.length; _j < _len1; i = ++_j) {
              subschema = _ref[i];
              select_dom.append($("<option value=\"" + i + "\">" + subschema.title + "</option>"));
              _results.push(generate(subschema, "" + path + "_" + i));
            }
            return _results;
          })();
          for (i = _j = 0, _len1 = options.length; _j < _len1; i = ++_j) {
            option = options[i];
            option_div = $("<div class=\"option\" id=\"" + i + "\"/>");
            dom.append(option_div.append(option.dom));
          }
          with_selected = (function() {
            var selected;
            selected = null;
            return {
              set: function(s) {
                if (s != null) {
                  selected = s;
                }
                dom.children(".option").css("display", "none");
                dom.children(".option#" + selected).css("display", "block");
                return select_dom.val(selected);
              },
              get: function() {
                return selected;
              }
            };
          })();
          with_selected.set(0);
          select_dom.change(function() {
            return with_selected.set(select_dom.val());
          });
          return {
            dom: dom.prepend(select_dom),
            set: function(x) {
              var _k, _len2, _ref;
              _ref = schema.type;
              for (i = _k = 0, _len2 = _ref.length; _k < _len2; i = ++_k) {
                subschema = _ref[i];
                if (!(type_match(x, subschema))) {
                  continue;
                }
                options[i].set(x);
                with_selected.set(i);
                break;
              }
            },
            get: function() {
              return options[with_selected.get()].get();
            }
          };
        } else {
          throw new Error("The type of " + (JSON.stringify(schema)) + " is not supported!");
        }
      });
    })();
  };

  logger = function(f) {
    return function() {
      var arg, args, res;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      res = f.apply(null, args);
      console.log("args: " + ((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = args.length; _i < _len; _i++) {
          arg = args[_i];
          _results.push(JSON.stringify(arg));
        }
        return _results;
      })()) + " = ", res);
      return res;
    };
  };

  type_match = (function() {
    var all, any, map, _ref;
    _ref = [_.all, _.any, _.map], all = _ref[0], any = _ref[1], map = _ref[2];
    return function(value, schema) {
      if (schema.type === "object" && _.isObject(value)) {
        return all(map(schema.properties, function(subschema, key) {
          return (function() {
            return (value[key] != null) && type_match(value[key], subschema);
          })();
        }));
      } else if (schema.type === "array" && _.isArray(value)) {
        return all(value, function(v) {
          return type_match(v, schema.items);
        });
      } else if (_.isArray(schema.type)) {
        return any(schema.type, function(s) {
          return type_match(value, s);
        });
      } else {
        return schema.type === "string" && _.isString(value) || schema.type === "bool" && _.isBoolean(value);
      }
    };
  })();

  examples = {
    union: {
      schema: {
        title: "Union type",
        type: [
          {
            title: "Checkbox",
            type: "bool"
          }, {
            title: "String",
            type: "string"
          }
        ]
      },
      value: "hello"
    },
    complex: {
      schema: {
        title: "Complex Schema",
        type: "object",
        properties: {
          extra: {
            title: "Extra Tags",
            type: "array",
            items: {
              title: "Extra Tag",
              type: "object",
              properties: {
                tag: {
                  title: "Tag Name",
                  type: "string"
                },
                attrs: {
                  title: "Attributes",
                  type: "array",
                  items: {
                    title: "Attribute",
                    type: "string"
                  }
                }
              }
            }
          }
        }
      },
      value: {
        extra: [
          {
            tag: "chapter",
            attrs: ["title", "author"]
          }, {
            tag: "header",
            attrs: ["date", "journal"]
          }
        ]
      }
    },
    object: {
      schema: {
        title: "Two objects",
        type: "object",
        properties: {
          name: {
            title: "Name",
            type: "string"
          },
          happy: {
            title: "Happy",
            type: "bool"
          }
        }
      },
      value: {
        name: "Test name",
        happy: true
      }
    },
    array: {
      schema: {
        title: "An array of strings",
        type: "array",
        items: {
          title: "A string in the array",
          type: "string",
          "default": "default string value"
        }
      },
      value: ["first string", "second string"]
    },
    string: {
      schema: {
        title: "A string",
        type: "string"
      },
      value: "a string value"
    },
    bool: {
      schema: {
        title: "A checkbox",
        type: "bool"
      },
      value: true
    }
  };

  examples.combine = {
    schema: {
      title: "All of them combined, as an array!!",
      description: "Might work!",
      type: 'array',
      items: {
        title: "An item!",
        type: _.values(_.pluck(examples, 'schema'))
      }
    },
    value: _.values(_.pluck(examples, 'value'))
  };

  test_examples = function() {
    return _.map(examples, function(example, key) {
      return console.log(key, type_match(example.value, example.schema));
    });
  };

}).call(this);
