// Generated by CoffeeScript 1.4.0
(function() {

  window.address = {};

  window.address.set_from_xml = function(data) {
    var build, new_hash, _ref;
    if (((_ref = (build = data != null ? data.getElementsByTagName("build") : void 0)) != null ? _ref.length : void 0) === 1) {
      new_hash = build[0].attributes.getNamedItem("hash").value;
      console.log("pushing bbq hash " + new_hash);
      return $.bbq.pushState({
        hash: new_hash
      });
    }
  };

  window.address.try_join_with_hash = function(xml_editor) {
    var hash;
    hash = $.bbq.getState("hash");
    if ((hash != null) && hash.length === 40) {
      return submit(xml_editor, false, hash);
    }
  };

}).call(this);
