// Generated by CoffeeScript 1.4.0
(function() {

  window.address = {};

  window.address.set_from_xml = function(data) {
    var build;
    if ((build = data.getElementsByTagName("build")).length === 1) {
      return window.location.hash = build[0].attributes.getNamedItem("hash").value;
    }
  };

  window.address.try_join_with_hash = function() {
    if (window.location.hash.length === 41 && window.location.hash[0] === '#') {
      return submit(void 0, false, window.location.hash.slice(1));
    }
  };

}).call(this);
