// Generated by CoffeeScript 1.4.0
(function() {
  var dismiss_button, show_errors;

  dismiss_button = function() {
    return $("<button type=\"button\" class=\"close\" data-dismiss=\"alert\">\n    <i class=\"icon-remove\"></i>\n</button>");
  };

  show_errors = function(data) {
    var error, error_div, errors, _i, _len;
    errors = data.getElementsByTagName("error");
    for (_i = 0, _len = errors.length; _i < _len; _i++) {
      error = errors[_i];
      console.log(error.textContent);
      error_div = $("<div class=\"alert alert-error\"/>");
      error_div.append(dismiss_button(), $("<span>Importkedjan gav följande varningar:</span>\n<pre class=\"original-pre\">" + error.textContent + "</pre>"));
      $("#errors").append(error_div);
    }
  };

  window.submit = function(xml_editor, makefile, join_with_hash) {
    var incremental, req_url, set, set_form_and_editor_when_joining, settings, text;
    if (makefile == null) {
      makefile = false;
    }
    if (join_with_hash == null) {
      join_with_hash = null;
    }
    settings = with_form.get();
    incremental = !makefile;
    text = join_with_hash ? "" : xml_editor.getValue();
    req_url = config.address;
    if (join_with_hash) {
      req_url += "/join?hash=" + join_with_hash;
    } else {
      if (makefile) {
        req_url += "/makefile";
      }
      req_url += "?settings=" + JSON.stringify(settings);
    }
    req_url += "&incremental=" + (String(incremental));
    if (incremental) {
      progress.initialize();
    }
    set = false;
    set_form_and_editor_when_joining = function(data_lazy) {
      var data, original, _ref, _ref1, _ref2, _ref3;
      if (!set && join_with_hash && (data = data_lazy())) {
        set = true;
        window.first_data = data;
        if (settings = (_ref = data.getElementsByTagName("settings")) != null ? (_ref1 = _ref[0]) != null ? _ref1.textContent : void 0 : void 0) {
          with_form.set(JSON.parse(settings));
        }
        if (original = (_ref2 = data.getElementsByTagName("original")) != null ? (_ref3 = _ref2[0]) != null ? _ref3.textContent : void 0 : void 0) {
          return xml_editor.setValue(original);
        }
      }
    };
    $.ajax({
      url: req_url,
      dataType: makefile ? "text" : "xml",
      timeout: 300000,
      type: "POST",
      data: text,
      success: function(data, textStatus, xhr) {
        set_form_and_editor_when_joining(function() {
          return data;
        });
        progress.clear();
        if (makefile) {
          $("#query").text(data);
        } else {
          show_errors(data);
          make_table(data);
        }
      },
      progress: function(data, e) {
        set_form_and_editor_when_joining(function() {
          return progress.complete_partial_xml(e.target.response);
        });
        if (incremental) {
          return progress.handle(e.target.response);
        }
      },
      error: function(jqXHR, textStatus, errorThrown) {
        progress.clear();
        return console.log("error", jqXHR, textStatus, errorThrown);
      }
    });
    return false;
  };

}).call(this);
